### ISSUE TITLE
Mudar o nome do Repositório

### ISSUE THREAD

**Issue by uira** [EscolaDeSaudePublica/MetodologiaDeDesenvolvimento#9]
Acho que esse repositório poderia ser renomeado para o devLab, e a Metodologia de Desenvolvimento ser um dos arquivos.

Quem concorda?

**Comment by camilaccolares** [comment]
@uira De acordo.

**Comment by oxechicao** [comment]
Poderia fazer o repositório uma página github onde os posts seriam arquivos escritos em Markdown, assim teria uma página bonitinha para visualização e ainda assim teriam os arquivos em markdown bem separados dentro do github.
Daria uma documentação mais organizada de ler. E poderia ter mais coisas além de metodologia de desenvolvimento.

**Comment by uira** [comment]
@chicaothiago Perfeito. Já cria um site do devLab

**Comment by uira** [comment]
![00-devLab](https://user-images.githubusercontent.com/89998/74538497-1ef05680-4f1b-11ea-8d0d-0fe2f63c35db.png)

**Comment by uira** [comment]
![00-devLab](https://user-images.githubusercontent.com/89998/74538880-dab18600-4f1b-11ea-858e-25c9ecc357c9.png)
